name: Deploy API to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Secrets (optional for troubleshooting)
      run: |
        echo "HOST: ${{ secrets.HOST }}"
        echo "USERNAME: ${{ secrets.USERNAME }}"

    - name: Set up SSH access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Prepare remote directory on VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rm -rf ~/simple-api && mkdir -p ~/simple-api"

    - name: Upload code to VM
      run: |
        scp app.py requirements.txt ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/simple-api/

    - name: Update system packages on VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo apt-get update"

    - name: Install pip on VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo apt-get install -y python3-pip"

    - name: Install Python dependencies on VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "pip3 install -r ~/simple-api/requirements.txt"

    - name: Stop any previous process on port 80
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo fuser -k 80/tcp || true"

    - name: Start Flask API on VM (port 80)
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ~/simple-api && sudo nohup python3 app.py > app.log 2>&1 &"
